language: python
dist: xenial

matrix:
  include:
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1
    # The pypy tests are slow, so we list them first
    - python: pypy3.5
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.5
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    # 3.5.0 and 3.5.1 have different __aiter__ semantics than all
    # other versions, so we need to test them specially. Travis's
    # xenial dist only provides 3.5.2+.
    - python: 3.5.0
      dist: trusty
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - os: osx
      language: generic
      env: MACPYTHON=3.5.4
    - os: osx
      language: generic
      env: MACPYTHON=3.6.7
    - os: osx
      language: generic
      env: MACPYTHON=3.7.1
    - os: osx
      language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6

script:
  - ci/travis.sh

branches:
  except:
    - /^dependabot/.*/
