language: python
python:
  - 3.5.0
  - 3.5.2
  - 3.6
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
sudo: false

matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      env: DOC_BUILD=1
    - os: linux
      language: generic
      env: USE_PYPY_NIGHTLY=1
    - os: osx
      language: generic
      env: MACPYTHON=3.5.3
    - os: osx
      language: generic
      env: MACPYTHON=3.6.0
  allow_failures:
    - env: USE_PYPY_NIGHTLY=1

script:
  - ci/travis.sh
