language: python
dist: xenial

matrix:
  include:
    - python: 3.8
      env: CHECK_DOCS=1
    - python: 3.8
      env: CHECK_FORMATTING=1
    # The pypy tests are slow, so we list them first
    - python: pypy3
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    # Qemu tests are also slow
    # The unique thing this provides is testing on the given distro's
    # kernel, which is important when we use new kernel features. This
    # is also good for testing the latest openssl etc., and getting
    # early warning of any issues that might happen in the next Ubuntu
    # LTS.
    - language: generic
      # We use bionic for the host, b/c rumor says that Travis's
      # 'bionic' systems have nested KVM enabled.
      dist: bionic
      env:
        - "JOB_NAME='Ubuntu 19.10, full VM'"
        - "VM_IMAGE=https://cloud-images.ubuntu.com/eoan/current/eoan-server-cloudimg-amd64.img"
    # 3.5.0 and 3.5.1 have different __aiter__ semantics than all
    # other versions, so we need to test them specially. Travis's
    # newer images only provide 3.5.2+, so we have to request the old
    # 'trusty' images.
    - python: 3.5.0
      dist: trusty
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
