name: Bump dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  bump:
    name: bump requirements
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Bump dependencies
        run: |
          python -m pip install -r test-requirements.txt
          pip-compile test-requirements.in
          pip-compile docs-requirements.in
      - name: Black
        run: |
          python -m pip install -r test-requirements.txt  # may contain new black ver
          black setup.py trio
      - name: Commit changes
        run: |
          git switch --force-create bump_from_${GITHUB_SHA:0:6}
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Dependency updates"
          gh pr create --base master --label dependencies \
              --title "Bump dependencies from commit ${GITHUB_SHA:0:6}" \
              --body ""
          # gh pr create returns before the pr is ready, we have to poll until success
          # https://github.com/cli/cli/issues/2619#issuecomment-1240543096        
          for BACKOFF in 1 2 4 8 15 15 15 15; do
              sleep $BACKOFF
              if gh pr merge --auto --squash; then
                  break
              fi
          done
          exit 1
